### ISSUE TITLE
Remove flashsocket from socket io options

### ISSUE THREAD

**Issue by jeena** [logsol/chuck.js#117]

**Comment by logsol** [comment]
you think we should, because of the block alert one of the testers got?

**Comment by jeena** [comment]
Yeah, if someone uses a browser without websockets it most probably isn't able to handle the game anyway.

**Comment by logsol** [comment]
Are you sure about that? I would say that socket.io should be pretty consistent. And old browser doesnt mean bad machine.

**Comment by jeena** [comment]
No I meant no websocket -> no webgl

**Comment by logsol** [comment]
but that's why we have the canvas renderer fallback in place

**Comment by jeena** [comment]
We decided to remove the flash socket so it would not show up and ask you to allow/block flash.
