### ISSUE TITLE
Test on older machines

### ISSUE THREAD

**Issue by jeena** [logsol/chuck.js#143]
One of the alpha players had an FPS of 3-5 after few rounds

**Comment by jeena** [comment]
I was testing around removing different things, I removed updating the physics and it (almost) didn't change the FPS, I removed the cammera and arrow glide, this didn't change the FPS either.

The thing which changed the FPS was not using webgl which made it much faster. And then also commenting out PixiView.renderer.render(stage) but still updating the physics the fps jumped from 30 to 57 FPS.

Also making the browser area half the size made the FPS go up to 57 too.

**Comment by logsol** [comment]
#127 could help a lot then

**Comment by logsol** [comment]
I consider this fixed. we should concentrate on #127 and reevaluate the issue after that.
