### ISSUE TITLE
Implement new RubeDoll

### ISSUE THREAD

**Issue by jeena** [logsol/chuck.js#151]
Related to #150. There's a branch for that: [ragdoll](https://github.com/logsol/chuck.js/tree/ragdoll)

**Comment by logsol** [comment]
almost finished, just need to position head joint in the middle of rubedoll rube file and swap pants image from left to right on flip.

**Comment by logsol** [comment]
done. 

I will close this issue for now, but i think #99 should be implemented before we merge this back to master
