### ISSUE TITLE
Uncaught type error: cannot read property CreateBody of undefined

### ISSUE THREAD

**Issue by jeena** [logsol/chuck.js#156]
Uncaught type error: cannot read property CreateBody of undefined, client.js 216 (compressed), use tag https://github.com/logsol/chuck.js/tree/v0.0.2

**Comment by logsol** [comment]
@jeena this might have been fixed by https://github.com/logsol/chuck.js/commit/3a5af058ef59f19e6759c7fc0aecfbf38c94d5d7 I believe that was the error message of the crash, mentioned in the commit description

**Comment by logsol** [comment]
I will close this - we'll reopen if we see the error again.
