### ISSUE TITLE
Idea for throwing ui

### ISSUE THREAD

**Issue by jeena** [logsol/chuck.js#59]
I just got an idea on how to unify throwing on all plattforms.

Instead of checking the distance from chuck to the mouse, the player should make a throwing gesture and it doesn't matter where on the screen.

What we would calculate then is the difference between the start and the end point. Start would be for example x,y from onmousedown and stop would be x,y from onmouse up. The same for touch devices and game pads.

**Comment by logsol** [comment]
I am considering this issue as resolved. We can add issues for gamepad and touch integrations later.
