### ISSUE TITLE
Reposition subbodies

### ISSUE THREAD

**Issue by logsol** [logsol/chuck.js#99]
when a ragdoll or a skateboard is moved away quickly from where it was created (e.g on user join) the joint has a lot of stress which ends up in a calculation overload of box2d. 

We should implement a gameobject setPosition method, which is used by the worldobject updater and all other positioning instances and should be extended by item classes that maintain subbodies.

**Comment by jeena** [comment]
Related to #151

**Comment by logsol** [comment]
We stopped here for today at trying to get limb 2d rotation transformation around the center of the chest.  box2d doesn't seem to implement a function like this.

branch: subbodies
